apiVersion: v1
kind: Service
metadata:
  name: testgoweb-service
  namespace: testgoweb
spec:
  type: NodePort
  selector:
    app: testgoweb
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000

